- hosts: all
  become: true
  tasks:
  - name: Remove older docker versions if present
    apt:
      pkg: '{{item}}'
      state: absent
    with_items:
    - docker
    - docker-engine
    - docker.io
    - containerd
    - runc

  - name: Install needed packages
    apt:
      update_cache: yes
      pkg:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
  
  - name: Add Docker's official apt key.
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
      state: present
    register: add_key
    ignore_errors: true
  
  - name: Add Docker stable repository.
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
      state: present
      update_cache: yes

  - name: Install Docker
    apt:
      name: "{{ item }}"
      state: latest
    with_items:
    - docker-ce 
    - docker-ce-cli
    - containerd.io
  
  - name: Creating docker group
    ansible.builtin.group:
      name: docker
      state: present
      
  - name: Adding user to docker group
    shell: |
      sudo usermod -aG docker $USER
      sudo mkdir /etc/docker
      cat <<EOF | sudo tee /etc/docker/daemon.json
      {
        "exec-opts": ["native.cgroupdriver=systemd"],
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "100m"
        },
        "storage-driver": "overlay2"
      }
      EOF

  - name: Restart service docker
    ansible.builtin.systemd:
      enabled: yes
      state: restarted
      daemon_reload: yes
      name: docker
